E0505 21:14:46.112471   36190 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"https://127.0.0.1:64248/api?timeout=32s\": dial tcp 127.0.0.1:64248: connect: connection refused"
E0505 21:14:46.113885   36190 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"https://127.0.0.1:64248/api?timeout=32s\": dial tcp 127.0.0.1:64248: connect: connection refused"
E0505 21:14:46.115235   36190 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"https://127.0.0.1:64248/api?timeout=32s\": dial tcp 127.0.0.1:64248: connect: connection refused"
E0505 21:14:46.116585   36190 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"https://127.0.0.1:64248/api?timeout=32s\": dial tcp 127.0.0.1:64248: connect: connection refused"
E0505 21:14:46.117922   36190 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"https://127.0.0.1:64248/api?timeout=32s\": dial tcp 127.0.0.1:64248: connect: connection refused"
The connection to the server 127.0.0.1:64248 was refused - did you specify the right host or port?
